[tool.poetry]
name = "swapi"
version = "0.1.0"
description = ""
authors = ["fury_cydonian"]

[tool.poetry.dependencies]
python = "^3.5"
requests = "^2.25.0"
pytest = "^6.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
